version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8087:8089" # Fixed extra quotation
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/testdb1" # Quoted value
      SPRING_DATASOURCE_USERNAME: devops_user
      SPRING_DATASOURCE_PASSWORD: devops_password
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "9091:80"
    environment:
      API_URL: "http://backend:8089/api"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mycloud_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: devops_password
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    name: mycloud_app_network
